### ISSUE TITLE
Unit Tests are not really atomic

### ISSUE THREAD

**Issue by Einenlum** [joffarex/php-calculator#4]
Right now when you test the Displayer, you are also testing the Calculator. It's a bit of an integration test instead of a unit test (which can be okay, depending on what you want to achieve).

If you follow [this advice](https://github.com/joffarex/php-calculator/issues/3), you can then inject a Mock Calculator in the Displayer.

Right now, if your DisplayerTest fails, it can be because the Calculator is wrongly calculating the values, but your Displayer class would work really well.

You can inject a mocked Calculator instead and then be sure that the thing you're testing is only your Displayer. More about Mocks in PHPUnit here: https://phpunit.de/manual/6.5/en/test-doubles.html

**Comment by joffarex** [comment]
Hey! I came across one problem with testing with mocked Calculator. 

Whenever I try to pass mocked object in the Display class in my DisplayTest, i get following error from my editor:

> Expected Type "App\CalculatorInterface". found "PHPUnit\Framework\MockObject\MockObject".

And test fails.

How exactly can I configure mock Calculator in order to test without any problems?

**Comment by Einenlum** [comment]
Two ways of doing this:

Using the `createMock` method:
```php
<?php

use App\CalculatorInterface;
use PHPUnit\Framework\TestCase;

use App\Displayer;

class DisplayerTest extends TestCase
{
  private $displayer;

  public function testDisplayerDisplayingSumOfTwoNumbers()
  {
    $calculator = $this->createMock(CalculatorInterface::class);
    $calculator->method('getSum')->willReturn(7);
    $this->displayer = new Displayer($calculator);

    $display = $this->displayer->displaySum(2, 5);
    $this->assertEquals("The sum of X and Y is: 7", $display);
  }
}
```

Using the prophesize method (which uses the great prophecy library under the hood):
```php
<?php

use App\CalculatorInterface;
use PHPUnit\Framework\TestCase;

use App\Displayer;

class DisplayerTest extends TestCase
{
  private $displayer;

  public function testDisplayerDisplayingSumOfTwoNumbers()
  {
    $calculator = $this->prophesize(CalculatorInterface::class);
    $calculator->getSum(2, 5)->willReturn(7);
    $this->displayer = new Displayer($calculator->reveal());

    $display = $this->displayer->displaySum(2, 5);
    $this->assertEquals("The sum of X and Y is: 7", $display);
  }
}
```

**Comment by joffarex** [comment]
Well, I tried first way and test passed, but editor is still giving me mentioned error. But still, Thanks, Ill Close this now as well.
